name: "CI Pipeline"

on:
  push:
    branches:
      - master

jobs:
  default:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false

      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
        operating-system:
          - "ubuntu-18.04"
          - "ubuntu-20.04"
          - "windows-2019"
          - "windows-2022"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup PHP Action"
        uses: shivammathur/setup-php@2.16.0
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer
      
      - name: "Composer Update"
        run: "composer update --no-interaction --no-progress"

      - name: "Unit Test"
        run: "vendor/bin/phpunit"
